<?php 


function tlm_translate_missing_node_view($node) {
	global $hasSaidFrenchNotAvailableAlready;
	//drupal_set_message(print_r(drupal_is_front_page(),true));
	
	//Dont perform this code for the front page.
	if(drupal_is_front_page()){
		return;		
	}
	
	
    global $language;
    //if (!empty($node->language) && $node->language != $language->language) {	//this doesnt work with the entitiy translation way.
    if(!$hasSaidFrenchNotAvailableAlready && isset($node) && isset($node->content['body']) && $node->content['body']['#language'] != $language->language) {
      $msg = t('Sorry, the page %title does not have an %language equivalent.', array('%title' => $node->title, '%language' => $language->native));
      drupal_set_message($msg, 'warning');
      $hasSaidFrenchNotAvailableAlready = true;
    }
}



//Hook into the menu_link theme hook so that we can pass the shortcuts link title thru the t() function for internatilization
function tlm_translate_missing_menu_link__shortcut_set_1($link){	
	$link['element']['#title'] = t($link['element']['#title']);
	
	return theme_menu_link($link);
}
function tlm_translate_missing_theme_registry_alter(&$theme){	//inject our handler into the hook theme registry so that its called no matter the theme. modules cant overwrite existing hooks easily, this is the only way.
	//drupal_set_message(print_r($theme,true));
	
	$theme['menu_link__shortcut_set_1'] = Array
        (
            'function' => 'tlm_translate_missing_menu_link__shortcut_set_1',
            'render element' => 'element',
            'base hook' => 'menu_link',
            'type' => 'theme_engine',
            'theme path' => 'sites/all/themes/pjct_2013',
            'preprocess functions' => Array( ),
            'process functions' => Array()
        );
}
?>